### ISSUE TITLE
Q. libft과제에서 작성하실때, 리팩토링을 한번 하신건가요?

### ISSUE THREAD

**Issue by exgs** [nadarm/42Seoul-42cursus#1]
안녕하세요. 42-algorithm을 따라서 오다보니 여기도 방문하게되었습니다.
저는 다시 42cursus과제를 진행하고자하는데, libft가 너무 오래되어 기억이 잘 나지않아 복습차원에서  
제 코드와 다른분들의 코드를 비교하고 있습니다.  

본론으로 들어가서, 제 코드와 다른 분들의 코드를 비교해보았을 때, 그 중에서 제가 고쳐야한다고 생각되는 부분은 함수를 만들어놓고 잘 활용하지 못했었다는 점입니다.  
nadaram님은 ft_strncmp나 ft_strdup ft_strchr은 다른 함수를 만들때도 종종 사용하셨던 것으로 보입니다.  
<u>제 질문은 그런 부분들이 코드 초안을 짤 때 부터 작성하기로 계획한 것인가요? 아니면 처음에는 다른 함수를 참조하지 않은 형태의 쌩코드(?)로 작성후에 **리팩토링**을 거친건가요?</u>
코딩하실때의 과정이 궁금해서 질문드립니다.
이 질문에 연장선상에는 RUSH할때, polarbear님이 프로그램을 만들기 앞서서 코드의 역활을 분할하는 밑그림을 먼저 그리라고 조언해주셨는데,  그 조언에도 아직 제 스타일은 **코딩후 수정**이기때문에 다른 분들은 어떤 과정을 거치는지 궁금합니다.  
(질문을 작성하면서, 갑자기 든 생각은 42-algorithm의 자료구조처럼 어떤 정해진 형태의 구조에서는 만들어 놓은 함수들의 집합체가 또 다른 함수가 되는 것이 당연한것처럼 함수의 참조는 프로그램이 커질 수록 필수라는 생각이 드네요... ex: create함수를 push에 활용하듯이)

**Comment by nadarm** [comment]
이미 만들어놓은 함수들은
비효율적이겠다 or 있는지 기억을 못함
같은 경우 아니면 사용하려고 노력하고 있어요

코딩할 때 이부분은 여러번 쓰일 것 같다 싶으면 바로 함수로 만들어요
그리고 처음에 생각 못한 코드라도 2~3번 중복되면 함수로 분리해요

코드를 한번 완성했다고 수정을 안하는게 아니라서
계획과 리팩토링 둘다 한다고 보시면 될 것 같아요

**Comment by nadarm** [comment]
보통 코드가 맘에 들 때까지 리팩토링 합니다
물론 계속 맘에 안들 때도 있지만... 그래도 최대한 맘에 들때까지 리팩토링해요

**Comment by exgs** [comment]
뮬리넷이 채점하지 못하는 유일한 부분을 코드리뷰와 리팩토링으로 보안하는 것이 마지막단계가 될 수 있겠다는 생각이 들었습니다. 감사합니다!
